print("Hello world!")
print("Hello-hello")
print("gfdgfg")
print("Hello friends!")
print("Це рядок Валерії")
print("adsdfdfjhgjsdkfgh")
print("Це рядок Роми")
print("This is my line)")

print ('NazarNazarNazarNazarNazarNazar')